### ISSUE TITLE
Compatibilità smartphones vs app C19

### ISSUE THREAD

**Issue by Joecratics** [jojo2234/GreenPass-Experiments#17]
Volevo segnalare un anomalia nella app C19
con un telefono ROOTED
HUAWEI P10 PLus 
build VKY-L29 8.0.0.386(C432)

Per pura prova ho provato ad editare direttamente il file .cose e il risultato con questo cell è che la verifica dopo la modifica risultava valida.
Ho provato anche l'app svizzera Covid check e anch'essa dava risultato positivo.

Le stesse app installate su di un HUAWEI P20 Lite UNROOTED danno (giustamente) risultato negativo e nello specifico quella svizzera dice firma non valida.

Grazie per qualsiasi risposta.

Joe

-------------------

I wanted to report an anomaly in the C19 verification app with a ROOTED phone HUAWEI P10 PLus build VKY-L29 8.0.0.386(C432).

For pure proof I tried to edit the.cose file directly and the result with this cell is that the verification after the change was valid.

I also tried the Swiss app Covid check and it also gave a positive result. The same apps installed on a HUAWEI P20 Lite UNROOTED give (rightly) negative result and specifically the Swiss one says invalid signature.

Thank you for any reply.

Joe

**Comment by jojo2234** [comment]
Grazie della segnalazione, archivio il problema.
