### ISSUE TITLE
errore java.security.NoSuchAlgorithmException: AndroidKeyStore KeyStore not available

### ISSUE THREAD

**Issue by misterx8** [jojo2234/GreenPass-Experiments#9]
Ciao,
Cercando di utilizzare le classi prelevate dal progetto c19 ufficiale(cartelle security) riscontro l'errore in oggetto quando cerco di ottenere: 
return KeyStore.getInstance(ANDROID_KEY_STORE).apply {
                this.load(null)

**Comment by jojo2234** [comment]
Attualmente la corretta decodifica delle chiavi non è funzionante, per questo è commentata. Ho inserito quella parte sotto forma di commento per dare la possibilità di accedere ai contenuti del database usando il file csv. Devo ancora lavorarci.
